add build for a rust compatible armhf-musl-gcc
swift-nav/swift-toolchains pull request #17
Opened 2023-04-23 01:16 UTC by isaactorz

The musl version in the rust toolchain is still based of musl libc v 1.1.x

This is not compatible with prebuilt musl toolchains that can be downloaded from the internet.

2023-04-24 16:25 UTC, silverjam requested changes
Would prefer if we use GitHub actions since this is a public repo-- we have access to s3 via the GitHub Actions AWS user/role that's setup in Terraform

2023-04-24 17:04 UTC, isaactorz commented
> Would prefer if we use GitHub actions since this is a public repo-- we have access to s3 via the GitHub Actions AWS user/role that's setup in Terraform

The main reason I went for jenkins is because we need to build against a compatible glib as we're using in the target CI environments (2.28).

Not impossible in GHA but it's a lot less ergonomic then how we have it set up in jenkins.

2023-04-25 08:18 UTC, krisukox approved these changes

2023-04-26 02:18 UTC, silverjam approved these changes

2023-04-26 20:21 UTC, merged